# coding: utf-8

"""
    AIHub API

    The AIHub REST API. Please see https://aihub.instabase.com/docs/ for more details.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from aihub.models.field import Field

class TestField(unittest.TestCase):
    """Field unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> Field:
        """Test Field
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `Field`
        """
        model = Field()
        if include_optional:
            return Field(
                value = '',
                type = '',
                confidence = aihub.models.field_confidence.Field_confidence(
                    model = 1.337, )
            )
        else:
            return Field(
        )
        """

    def testField(self):
        """Test Field"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
