# coding: utf-8

"""
    AIHub API

    The AIHub REST API. Please see https://aihub.instabase.com/docs/ for more details.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from aihub.models.conversation_response import ConversationResponse

class TestConversationResponse(unittest.TestCase):
    """ConversationResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ConversationResponse:
        """Test ConversationResponse
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ConversationResponse`
        """
        model = ConversationResponse()
        if include_optional:
            return ConversationResponse(
                id = '',
                name = '',
                upload_status = aihub.models.conversation_response_upload_status.conversationResponse_upload_status(
                    success = [
                        aihub.models.conversation_response_upload_status_success_inner.conversationResponse_upload_status_success_inner(
                            name = '', )
                        ], 
                    failure = [
                        aihub.models.conversation_response_upload_status_failure_inner.conversationResponse_upload_status_failure_inner(
                            name = '', )
                        ], )
            )
        else:
            return ConversationResponse(
                id = '',
                name = '',
                upload_status = aihub.models.conversation_response_upload_status.conversationResponse_upload_status(
                    success = [
                        aihub.models.conversation_response_upload_status_success_inner.conversationResponse_upload_status_success_inner(
                            name = '', )
                        ], 
                    failure = [
                        aihub.models.conversation_response_upload_status_failure_inner.conversationResponse_upload_status_failure_inner(
                            name = '', )
                        ], ),
        )
        """

    def testConversationResponse(self):
        """Test ConversationResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
