# coding: utf-8

"""
    AIHub API

    The AIHub REST API. Please see https://aihub.instabase.com/docs/ for more details.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from aihub.models.conversation import Conversation

class TestConversation(unittest.TestCase):
    """Conversation unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> Conversation:
        """Test Conversation
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `Conversation`
        """
        model = Conversation()
        if include_optional:
            return Conversation(
                id = '',
                name = '',
                description = '',
                state = '',
                documents = [
                    aihub.models.document_details.documentDetails(
                        id = 56, 
                        name = '', 
                        state = '', 
                        upload_timestamp = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), )
                    ]
            )
        else:
            return Conversation(
                id = '',
                name = '',
                state = '',
        )
        """

    def testConversation(self):
        """Test Conversation"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
