# coding: utf-8

"""
    AIHub API

    The AIHub REST API. Please see https://aihub.instabase.com/docs/ for more details.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from aihub.api.default_api import DefaultApi


class TestDefaultApi(unittest.TestCase):
    """DefaultApi unit test stubs"""

    def setUp(self) -> None:
        self.api = DefaultApi()

    def tearDown(self) -> None:
        pass

    def test_add_file_to_batch(self) -> None:
        """Test case for add_file_to_batch

        Upload a file to the batch.
        """
        pass

    def test_converse(self) -> None:
        """Test case for converse

        Converse with the documents in a conversation.
        """
        pass

    def test_create_batch(self) -> None:
        """Test case for create_batch

        Create a new batch.
        """
        pass

    def test_create_conversation(self) -> None:
        """Test case for create_conversation

        Create a new conversation and upload files.
        """
        pass

    def test_get_conversation(self) -> None:
        """Test case for get_conversation

        Get the details of the conversation.
        """
        pass

    def test_get_run_results(self) -> None:
        """Test case for get_run_results

        Retrieve run results
        """
        pass

    def test_get_run_status(self) -> None:
        """Test case for get_run_status

        Get the status of a run.
        """
        pass

    def test_list_conversations(self) -> None:
        """Test case for list_conversations

        List all conversations created.
        """
        pass

    def test_run_app(self) -> None:
        """Test case for run_app

        Run a given app.
        """
        pass


if __name__ == '__main__':
    unittest.main()
